cpp_files=sim_main.cpp
files=../../src/armleocpu_regfile_single_lane.v
files+=../../src/armleocpu_regfile.v
verilator_options=-Wno-UNOPTFLAT
top=armleocpu_regfile
include ../VerilatorSimulate.mk
