###############################################################################


cpp_files=sim_main.cpp
defines=-DDEBUG_EXECUTE
top=armleocpu_execute
files=$(EXECUTE_FILES)

include $(PROJECT_DIR)/tests/VerilatorCXXTestbenchTemplate.mk
