tbfiles=mem_cells_tb.v
files=../../../core_src/armleocpu_mem_1rw.v ../../../core_src/armleocpu_mem_1rwm.v

default: clean test
test: simulate-iverilog
clean: clean-iverilog

include ../../SimulateTemplate.mk
