cpp_files=sim_main.cpp
files=
files+=../../src/armleocpu_brcond.v
files+=../../src/armleocpu_alu.v
files+=../../src/armleocpu_unsigned_divider.v
files+=../../src/armleocpu_multiplier.v
files+=../../src/armleocpu_execute.v
includepaths=../../src/
defines=-DDEBUG_EXECUTE
top=armleocpu_execute
include ../../VerilatorSimulate.mk