cpp_files=sim_main.cpp
files=../../src/armleocpu_cache.v ../../src/armleocpu_cache_pagefault.v ../../src/armleocpu_ptw.v ../../src/armleocpu_tlb.v ../../src/armleocpu_loadgen.v ../../src/armleocpu_storegen.v ../../src/mem_1w1r.v
includepaths=../../src/
defines=-DDEBUG_CACHE -DDEBUG_PAGEFAULT -DDEBUG_PTW
verilator_options=-Wno-UNOPTFLAT -Wno-DECLFILENAME
top=armleocpu_cache
include ../VerilatorSimulate.mk