cpp_files=sim_main.cpp
files=../../src/corevx_cache.v ../../src/corevx_cache_pagefault.v ../../src/corevx_ptw.v ../../src/corevx_tlb.v ../../src/corevx_loadgen.v ../../src/corevx_storegen.v ../../src/mem_1w1r.v
includepaths=../../src/
defines=-DDEBUG_CACHE -DDEBUG_PAGEFAULT -DDEBUG_PTW
top=corevx_cache
include ../VerilatorSimulate.mk