cpp_files=sim_main.cpp
files=../../src/corevx_cache.sv ../../src/corevx_cache_pagefault.sv ../../src/corevx_ptw.sv ../../src/corevx_tlb.sv ../../src/corevx_loadgen.sv ../../src/corevx_storegen.sv ../../src/mem_1w1r.sv
includepaths=../../src/
top=corevx_cache
include ../VerilatorSimulate.mk