tbfiles=cache_pagefault_tb.v
files=../../../core_src/armleocpu_cache_pagefault.v
defines=-DDEBUG_PAGEFAULT

default: clean test
test: simulate-iverilog
clean: clean-iverilog

include ../../SimulateTemplate.mk
