tbfiles=cache_tb.v
files=../../src/armleocpu_mem_1rw.v
files+=../../src/armleocpu_mem_1rwm.v
files+=../../src/armleocpu_cache_pagefault.v
files+=../../src/armleocpu_ptw.v
files+=../../src/armleocpu_tlb.v
files+=../../src/armleocpu_loadgen.v
files+=../../src/armleocpu_storegen.v
files+=../../src/armleocpu_cache.v

include ../SimulateTemplate.mk