tbfiles=corevx_cache_tb.sv
files=../../src/corevx_cache.sv ../../src/corevx_cache_pagefault.sv ../../src/corevx_ptw.sv ../../src/corevx_tlb.sv ../../src/corevx_tlb_way.sv ../../src/corevx_loadgen.sv ../../src/corevx_storegen.sv ../../src/mem_1w1r.sv ../armleobus_scratchmem/armleobus_scratchmem.sv
includepaths=../../src/
include ../SimulateTemplate.mk