###############################################################################

tbfiles=jtag_tap_tb.v
top=armleocpu_jtag_tap
defines=-DDEBUG_JTAG_TAP
files=$(JTAG_TAP_FILES)

include $(PROJECT_DIR)/tests/VerilogTestbenchTemplate.mk
