tbfiles=axi_bram_tb.v
files=../../../peripheral_src/armleocpu_axi_bram.v ../../../core_src/armleocpu_mem_1rw.v ../../../core_src/armleocpu_mem_1rwm.v
defines=-DBRAM_DEBUG
include ../../SimulateTemplate.mk
