###############################################################################

cpp_files=sim_main.cpp
defines=-DDEBUG_CACHE -DFORMAL_RULES
top=armleocpu_cache
files=$(CACHE_FILES) $(BRAM_ONLY_FILES)

include $(PROJECT_DIR)/tests/VerilatorCXXTestbenchTemplate.mk