cpp_files=sim_main.cpp
files=../../src/corevx_execute.sv ../../src/corevx_brcond.sv ../../src/corevx_alu.sv ../../src/corevx_immgen.sv
includepaths=../../src/
defines=-DDEBUG_EXECUTE
top=corevx_execute
include ../VerilatorSimulate.mk