cpp_files=sim_main.cpp
files=../../src/corevx_execute.v ../../src/corevx_brcond.v ../../src/corevx_alu.v
includepaths=../../src/
defines=-DDEBUG_EXECUTE
top=corevx_execute
include ../VerilatorSimulate.mk