###############################################################################

tbfiles=jtag_dtm_tb.v
top=armleocpu_jtag_dtm
defines=-DDEBUG_JTAG_DTM
files=$(JTAG_DTM_FILES)

include $(PROJECT_DIR)/tests/VerilogTestbenchTemplate.mk
