cpp_files=sim_main.cpp
files=../../src/armleocpu.v ../../src/armleocpu_regfile.v ../../src/armleocpu_alu.v ../../src/armleocpu_brcond.v ../../src/armleocpu_execute.v ../../src/armleocpu_fetch.v ../../src/armleocpu_cache.v ../../src/armleocpu_cache_pagefault.v ../../src/armleocpu_ptw.v ../../src/armleocpu_tlb.v ../../src/armleocpu_loadgen.v ../../src/armleocpu_storegen.v ../../src/mem_1w1r.v
includepaths=../../src/
defines=-DDEBUG_CACHE -DDEBUG_EXECUTE -DDEBUG_FETCH
top=armleocpu
include ../VerilatorSimulate.mk