name: Testts CI

on:
  push:
    branches:
      - 'main-development'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: WORKSPACE=${{GITHUB_WORKSPACE}}