name: Tests CI

on:
  push:
    branches:
      - 'main-development'

jobs:
  test_all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: make